name: Spring Boot Testing

on:
  push:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Obtener los últimos cambios del proyecto
      uses: actions/checkout@v4

    - name: Instalar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
      
    - name: Configurar gradle
      uses: gradle/gradle-build-action@v2

    - name: Compilar el proyecto
      run: ./gradlew build

    - name: Verificación del Code Coverage
      run: ./gradlew jacocoTestCoverageVerification